name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    name: 🔨 Build & 🔬 Test
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🔧 Use .NET Core 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"
      - name: 🔩 Restore dependencies
        run: dotnet restore ./Tethos.sln
      - name: 🔨 Build
        run: dotnet build ./Tethos.sln --configuration Release --no-restore
      - name: 🔬 Test
        run: dotnet test ./Tethos.sln --configuration Release --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx --results-directory ./coverage
      - name: 🔍 Coverage
        uses: codecov/codecov-action@v2
        with:
          verbose: true
      - name: 📚 Artifact
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: coverage/*.trx
