name: "🔄 CI"

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  build:
    name: 🔨 Build
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔙 Get Previous Version
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      - name: 🔨 Build
        run: dotnet build ./Tethos.sln --configuration Release -p:Version=$(echo ${{ steps.previoustag.outputs.tag }} | tr -d 'v')

      - name: 📚 Artifact NuGet
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: nuget-packages
          path: |
            src/**/Tethos*.nupkg
            src/**/Tethos*.snupkg

  test:
    name: 🔬 Test
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔬 Test with SonarCloud
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: highbyte/sonarscan-dotnet@v2.1.2
        with:
          sonarProjectKey: iamdmitrij_Tethos
          sonarProjectName: Tethos
          sonarOrganization: iamdmitrij
          dotnetBuildArguments: ./Tethos.sln --configuration Release
          dotnetTestArguments: ./Tethos.sln --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover --logger trx --results-directory ./coverage
          sonarBeginArguments: /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml" /d:sonar.cs.vstest.reportsPaths="coverage/*.trx" /d:sonar.coverage.exclusions="test/**, demo/**"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔍 Coverage
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: codecov/codecov-action@v2
        with:
          verbose: true

      - name: 📚 Artifact Test Results
        uses: actions/upload-artifact@v2
        if: success() || failure()
        with:
          name: test-results
          path: coverage/*.trx

  spellcheck:
    name: 🔦 Spellcheck
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: ✅ Check spelling
        uses: check-spelling/check-spelling@v0.0.20-alpha3
        with:
          extra_dictionaries: cspell:csharp/csharp.txt
            cspell:companies/companies.txt
            cspell:dotnet/dotnet.txt
            cspell:filetypes/filetypes.txt
            cspell:fullstack/fullstack.txt
            cspell:html/html.txt
            cspell:software-terms/software-terms.txt
