name: NuGet

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    name: 📦 Publish to NuGet
    runs-on: windows-latest

    steps:
      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ci.yml
          name: nuget-packages

      - name: 🔨 Use .NET Core 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Get tag
        id: tag
        uses: dawidd6/action-get-tag@v1
        with:
          strip_v: false

      - name: Use tag
        run: echo ${{steps.tag.outputs.tag}}

      - name: 🎁 Push to NuGet
        run: dotnet nuget push **/Tethos.*.nupkg --source ${{ secrets.NUGET_FEED }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
