name: nuget

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: 🔨 Use .NET Core 5.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "5.0.x"

      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      # - name: Push Tethos NuGet
      #   run: dotnet nuget push src/Tethos/bin/Debug/Tethos.*.nupkg --source ${{ secrets.NUGET_FEED }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
      # - name: Push Tethos.Moq NuGet
      #   run: dotnet nuget push src/Tethos.Moq/bin/Debug/Tethos.Moq.*.nupkg --source ${{ secrets.NUGET_FEED }} --api-key ${{ secrets.NUGET_API_KEY }} --skip-duplicate
