name: "🏅 Performance Report"

on:
  workflow_run:
    workflows: ["🏄 Performance"]
    types: ["completed"]
jobs:
  report:
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.event == 'pull_request' }}
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - uses: dawidd6/action-download-artifact@v2
        with:
          workflow: performance.yml
          name: performance-test-results

      - name: 📑 Aggregate results
        run: cat **/Tethos.*.Tests.Benchmarks.*.md > results.md

      - name: 🔟 Resolve Pull Request Reference
        id: pr_number
        uses: juliangruber/read-file-action@v1.0.0
        with:
          path: pr_number.meta

      - name: 🏅 Read test results
        uses: pCYSl5EDgo/cat@master
        id: benchmark
        with:
          path: results.md

      - name: 📬 Find Comment
        uses: peter-evans/find-comment@v1
        id: fc
        with:
          issue-number: ${{ steps.pr_number.outputs.content }}
          comment-author: "github-actions[bot]"
          body-includes: 🏅 Performance test report
          direction: last

      - name: 📝 Create comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          body: |
            # 🏅 Performance test report

            <details closed><summary>Expand to see results 🔽</summary>

            ${{ steps.benchmark.outputs.text }}

            </details>
          issue-number: ${{ steps.pr_number.outputs.content }}
          comment-id: ${{ steps.fc.outputs.comment-id }}
          edit-mode: "replace"
