name: "💣 Snyk"

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  security-scan:
    name: 🔍 Security scan
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔨 Build
        run: dotnet build ./Tethos.sln --configuration Release

      - name: 🔓 Run Snyk scan
        if: ${{ github.actor != 'dependabot[bot]' }}
        uses: snyk/actions/dotnet@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --all-projects --severity-threshold=critical
