name: "🎳 Stryker"

on:
  push:
    tags: ["v[1-9]+.[0-9]+.[0-9]"]
  pull_request:
    branches: ["main"]
    types: ["opened", "synchronize", "reopened"]

jobs:
  save-metadata:
    name: 🔽 Save metadata
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔖 Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 🔟 Save Pull Request Number
        shell: bash
        env:
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: echo $PR_NUMBER > pr_number.meta

      - name: 🔟 Save Branch Name
        shell: bash
        run: echo ${{ steps.branch-name.outputs.current_branch }} | tr -d '\n' > branch.meta

      - name: 📚 Test results
        uses: actions/upload-artifact@v2
        with:
          name: stryker-results
          path: "**/*.meta"

  mutation-tests:
    name: 💀 Tethos
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔦 Restore tools
        run: dotnet tool restore

      - name: 🔖 Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 💀 Run mutation tests
        shell: bash
        run: >
          is_tag=${{ steps.branch-name.outputs.is_tag }}
          target_branch=${{ steps.branch-name.outputs.current_branch }}
          extra_reporter="dashboard"

          if [ "$is_tag" = true ]; then
            target_branch="main"
          fi

          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            extra_reporter="cleartext"
          fi

          dotnet stryker --config-file test/Tethos.Tests/stryker-config.json
          --version "$target_branch"
          --reporter "$extra_reporter"
          --reporter "cleartext"
          --reporter "html"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: 📚 Test results
        uses: actions/upload-artifact@v2
        with:
          name: stryker-results
          path: "**/StrykerOutput/**"

  mutation-tests-moq:
    name: 💀 Tethos.Moq
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔦 Restore tools
        run: dotnet tool restore

      - name: 🔖 Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 💀 Run mutation tests
        shell: bash
        run: >
          is_tag=${{ steps.branch-name.outputs.is_tag }}
          target_branch=${{ steps.branch-name.outputs.current_branch }}
          extra_reporter="dashboard"

          if [ "$is_tag" = true ]; then
            target_branch="main"
          fi

          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            extra_reporter="cleartext"
          fi

          dotnet stryker --config-file test/Tethos.Moq.Tests/stryker-config.json
          --version "$target_branch"
          --reporter "$extra_reporter"
          --reporter "cleartext"
          --reporter "html"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: 📚 Test results
        uses: actions/upload-artifact@v2
        with:
          name: stryker-results
          path: "**/StrykerOutput/**"

  mutation-tests-fakeiteasy:
    name: 💀 Tethos.FakeItEasy
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔦 Restore tools
        run: dotnet tool restore

      - name: 🔖 Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 💀 Run mutation tests
        shell: bash
        run: >
          is_tag=${{ steps.branch-name.outputs.is_tag }}
          target_branch=${{ steps.branch-name.outputs.current_branch }}
          extra_reporter="dashboard"

          if [ "$is_tag" = true ]; then
            target_branch="main"
          fi

          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            extra_reporter="cleartext"
          fi

          dotnet stryker --config-file test/Tethos.FakeItEasy.Tests/stryker-config.json
          --version "$target_branch"
          --reporter "$extra_reporter"
          --reporter "cleartext"
          --reporter "html"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: 📚 Test results
        uses: actions/upload-artifact@v2
        with:
          name: stryker-results
          path: "**/StrykerOutput/**"

  mutation-tests-nsubstitute:
    name: 💀 Tethos.NSubstitute
    runs-on: windows-latest
    steps:
      - name: 📥 Checkout
        uses: actions/checkout@v2

      - name: 🔧 Use .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: 🔦 Restore tools
        run: dotnet tool restore

      - name: 🔖 Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5

      - name: 💀 Run mutation tests
        shell: bash
        run: >
          is_tag=${{ steps.branch-name.outputs.is_tag }}
          target_branch=${{ steps.branch-name.outputs.current_branch }}
          extra_reporter="dashboard"

          if [ "$is_tag" = true ]; then
            target_branch="main"
          fi

          if [[ "$GITHUB_ACTOR" == "dependabot[bot]" ]]; then
            extra_reporter="cleartext"
          fi

          dotnet stryker --config-file test/Tethos.NSubstitute.Tests/stryker-config.json
          --version "$target_branch"
          --reporter "$extra_reporter"
          --reporter "cleartext"
          --reporter "html"
        env:
          STRYKER_DASHBOARD_API_KEY: ${{ secrets.STRYKER_DASHBOARD_API_KEY }}

      - name: 📚 Test results
        uses: actions/upload-artifact@v2
        with:
          name: stryker-results
          path: "**/StrykerOutput/**"
